# Generated by Django 3.0.3 on 2020-02-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('source', models.CharField(default='凭空捏造', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=10, verbose_name='选项')),
                ('votenums', models.PositiveIntegerField(default=0, verbose_name='票数')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='vote.Problem', verbose_name='所属问题')),
            ],
        ),
    ]
