# Generated by Django 3.0.4 on 2020-03-09 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='汽车名称')),
                ('group_id', models.CharField(max_length=10, verbose_name='汽车车牌')),
                ('displacement', models.CharField(max_length=10, verbose_name='排放量')),
                ('transmission_name', models.CharField(max_length=10, verbose_name='驾驶方式')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField(verbose_name='经度')),
                ('lat', models.FloatField(verbose_name='维度')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveIntegerField(verbose_name='元/小时')),
                ('day', models.PositiveIntegerField(verbose_name='元/天')),
                ('week', models.PositiveIntegerField(verbose_name='元/周')),
                ('month', models.PositiveIntegerField(verbose_name='元/月')),
                ('avg', models.PositiveIntegerField(verbose_name='元/日均')),
                ('minimum', models.PositiveIntegerField(verbose_name='最短起租时间')),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='门店名称')),
                ('address', models.CharField(max_length=20, verbose_name='门店地址')),
                ('phone', models.CharField(max_length=20, verbose_name='座机电话')),
                ('site_phone', models.CharField(max_length=20, verbose_name='移动电话')),
                ('from_time', models.TimeField(verbose_name='上班时间')),
                ('to_time', models.TimeField(verbose_name='下班时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='rentcar.City', verbose_name='所在城市')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='coordinate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='rentcar.Location', verbose_name='坐标'),
        ),
        migrations.CreateModel(
            name='Carimgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='carimgs')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='rentcar.Car', verbose_name='所属车辆')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='rentcar.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.ManyToManyField(to='rentcar.Prices', verbose_name='价格'),
        ),
    ]
