# Generated by Django 3.0.3 on 2020-02-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option2',
            field=models.IntegerField(default=0, max_length=10, verbose_name='反对'),
        ),
    ]
