# Generated by Django 3.0.3 on 2020-03-02 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='员工名')),
                ('wages', models.PositiveIntegerField(max_length=10, verbose_name='本月工资')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wages.Department', verbose_name='所属部门')),
            ],
        ),
    ]
